# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
        
        CREATE TABLE `eld_table` (
  `eld_id` int(11) NOT NULL AUTO_INCREMENT,
  `eld_registration_id` int(11) DEFAULT NULL,
  `eld_identifier` int(11) DEFAULT NULL,
  `eld_auth_value` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`eld_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1020 DEFAULT CHARSET=utf8;
        
                """)
    ]
